# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0f86ea835ce5dfadd4a0e19f6cbb5bc083dd47cd27d2797a5567705d8c1d40d73190e4b9841f8f06ac0e615bff6dd2d801b48c851c20ba2f3f4585a5e3af32c

test:
  secret_key_base: f7185b8d44c8b96a5071ac712c0ebdb268da5f63d57c60ff460690e6c6f9875fbb3c45d07b3ae7ca478884ecaf84a1efd5ca2eb2f7b9727fe56da1bb3492a7d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: d23373ac3ef3bf7d452a3d2ebfe32fd467f97dadc927c10646daba2563ea857904c57acf57f64a06c8f6eca2f6b2d36821b0daff3b012e22e03cab0662b7c4c9
